<?php

return [
    'mode'                  => env('DOMPDF_MODE', 'utf-8'),
    'defines'               => [
        'DOMPDF_TEMP_DIR'   => storage_path('app'),
        'DOMPDF_CHROOT'     => public_path(),
        'DOMPDF_LOG_OUTPUT_FILE' => storage_path('logs/dompdf.log'),
    ],
    'convert_entities'      => true,
    'protocol'              => env('APP_URL', 'http://localhost'),
    'http_context'          => [
        'ssl' => [
            'allow_self_signed' => true,
            'verify_peer'       => false,
            'verify_peer_name'  => false,
        ]
    ],
    'postScriptLoader'      => null,
    'defaultMediaType'      => env('DOMPDF_MEDIA_TYPE', 'screen'),
    'defaultPaperSize'      => env('DOMPDF_PAPER_SIZE', 'A4'),
    'margin_top'            => env('DOMPDF_MARGIN_TOP', 0),
    'margin_right'          => env('DOMPDF_MARGIN_RIGHT', 0),
    'margin_bottom'         => env('DOMPDF_MARGIN_BOTTOM', 0),
    'margin_left'           => env('DOMPDF_MARGIN_LEFT', 0),
    'isPhpEnabled'          => env('DOMPDF_PHP_ENABLED', false),
    'isRemoteEnabled'       => env('DOMPDF_REMOTE_ENABLED', true),
    'isJavascriptEnabled'   => env('DOMPDF_JAVASCRIPT_ENABLED', true),
    'isHtmlEntitiesEnabled' => env('DOMPDF_HTML_ENTITIES_ENABLED', true),
    'isFontSubsettingEnabled' => env('DOMPDF_FONT_SUBSETTING_ENABLED', true),
    'enablePhp'             => env('DOMPDF_ENABLE_PHP', false),
    'enableJavascript'      => env('DOMPDF_ENABLE_JAVASCRIPT', true),
    'debugPNG'              => env('DOMPDF_DEBUG_PNG', false),
    'debugKeepTemp'         => env('DOMPDF_DEBUG_KEEP_TEMP', false),
    'debugCss'              => env('DOMPDF_DEBUG_CSS', false),
    'debugLayout'           => env('DOMPDF_DEBUG_LAYOUT', false),
    'debugLayoutLines'      => env('DOMPDF_DEBUG_LAYOUT_LINES', true),
    'debugLayoutBlocks'     => env('DOMPDF_DEBUG_LAYOUT_BLOCKS', true),
    'debugLayoutInline'     => env('DOMPDF_DEBUG_LAYOUT_INLINE', true),
    'debugLayoutPaddingBox' => env('DOMPDF_DEBUG_LAYOUT_PADDING_BOX', true),
    'pdfBackend'            => env('DOMPDF_PDF_BACKEND', 'CPDF'),
    'pdflibLicense'         => env('DOMPDF_PDFLIB_LICENSE', ''),
    'adminEmail'            => env('ADMIN_EMAIL', 'admin@example.com'),
    'buyLicense'            => true,
    'cachePath'             => env('DOMPDF_CACHE_PATH', storage_path('app/dompdf')),
    'cacheTTL'              => env('DOMPDF_CACHE_TTL', 86400 * 365),
    'tempDir'               => env('DOMPDF_TEMP_DIR', storage_path('app')),
    'fontDir'               => env('DOMPDF_FONT_DIR', storage_path('fonts')),
    'fontCache'             => env('DOMPDF_FONT_CACHE', storage_path('fonts')),
    'chroot'                => env('DOMPDF_CHROOT', public_path()),
    'allowedProtocols'      => [
        'http'  => ['streams' => true],
        'https' => ['streams' => true],
        'file'  => ['streams' => true],
    ],
    'logOutputFile'         => env('DOMPDF_LOG_OUTPUT_FILE', null),
    'defaultFont'           => env('DOMPDF_DEFAULT_FONT', 'Helvetica'),
    'dpi'                   => env('DOMPDF_DPI', 96),
    'fontHeightRatio'       => env('DOMPDF_FONT_HEIGHT_RATIO', 1.1),
    'pdfVersion'            => env('DOMPDF_PDF_VERSION', '1.7'),
];
